server:
  port: 8090

logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messages
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update